#ifndef CMDDEF_H
#define CMDDEF_H
#define GET "GET"
#define HANDIN "HANDIN"

#define POSI_INFO "POSITION INFO"
#define GOOD_INFO "GOOD INFO"
#define USR_EXCEPT "USER EXCEPTION"
#define DIARY "DIARY"
#define DIARIES "DIARIES"
#define DIA_CON "DIARY CONTENT"

#define NOTHING "NOTHING"
#define OK "OK"
#define EXCEP_STRUCT_SIZE 8
#define DIARY_STRUCT_SIZE 5
#endif // CMDDEF_H
