#ifndef CMDDEF_H
#define CMDDEF_H
#define GET "GET"
#define HANDIN "HANDIN"

#define POSI_INFO "POSITION_INFO"
#define GOOD_INFO "GOOD_INFO"
#define CUR_STATUS "CUR_STATUS"
#define USR_EXCEPT "USER_EXCEPTION"

#define DIARY "DIARY"
#define DIARIES "DIARIES"
#define DIA_CON "DIARY_CONTENT"

#define THIS_MONTH_THROUGHOUT "TMT"
#define NEXT_MONTH_THROUGHOUT   "NMT"
#define COMPANY_BUSY_RANK   "COMPANY_B_RANK"
#define GOOD_WASTAGE    "GOOD_WASTAGE"

#define NOTHING "NOTHING"
#define OK "OK"
#define EXCEP_STRUCT_SIZE 8
#define DIARY_STRUCT_SIZE 4
#endif // CMDDEF_H
